name: Publish package to GitHub Packages
on:
  push:
    branches: [release]
  pull_request:
    branches: [release]
  release:
    types: [created]
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Publish package
        run: |
            mvn -B versions:set -DnewVersion=$GITHUB_SHA -DgenerateBackupPoms=false
            mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
